# -*- coding: utf-8 -*-
"""7. Reverse Integer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-8n0HQm_khgIeMgb-ne-vcMOpUSkKEf8
"""

class Solution:
    def reverse(self, x: int) -> int:
        if x < -2**31 or x > 2**31-1:
            return 0
        
        res = 0
        d = 0
        if x < 0:
            s = str(x)[1:]
        else:
            s = str(x)
        
        for i in range(len(s)-1,-1,-1):
            dig = s[i]
            res = res*10+int(dig)

        if x< 0:
            res = -res
        
        if res < -2**31 or res > 2**31-1:
            return 0
        return res