# -*- coding: utf-8 -*-
"""9. Palindrome Number.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u9hUUFxlE4BHc1yCDf5lN-9bKbl8-Hqa
"""

class Solution:
    def isPalindrome(self, x: int) -> bool:
        if x<0:
            return False
        else:
            x = str(x)
            if len(x) == 1:
                return True
            else:
                l = len(x)//2
                for i in range(l+1):
                    if x[i] != x[-1-i]:
                        return False
            return True