# -*- coding: utf-8 -*-
"""14. Longest Common Prefix.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/163D-yPXgESDVhDEQ4FjIhRGkNIew-Z17
"""

class Solution:
    def longestCommonPrefix(self, strs: List[str]) -> str:
        st = strs[0]
        for i in range(0,len(strs)):
            j = 0
            k = min(len(st), len(strs[i]))
            
            while (j < k and st[j] == strs[i][j]):
                j += 1
        
            st = st[:j]
            
        return st