# -*- coding: utf-8 -*-
"""1. Two Sum.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fgJ0NSSORAShY_IMZ-5pVxcQqDehzaS4
"""

class Solution:
    def twoSum(self, nums: List[int], target: int) -> List[int]:
        
        h={}
        for i,value in enumerate(nums):
            d=target-value
            if d in h:
                return [h[d],i]
            h[value]=i
        return