# -*- coding: utf-8 -*-
"""22. Generate Parentheses.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SorJSy1feeSVilHfLcszwZkA2jVGosNR
"""

class Solution:
    def generateParenthesis(self, n: int) -> List[str]:
        
        stack = []
        result = []

        def backtracking(openedNum, closedNum):
            if openedNum == closedNum == n:
                result.append("".join(stack))
                return result

            if openedNum < n:
                stack.append("(")
                backtracking(openedNum + 1, closedNum)
                stack.pop()
            if closedNum < openedNum:
                stack.append(")")
                backtracking(openedNum, closedNum + 1)
                stack.pop()

        backtracking(0, 0)
        return result