# -*- coding: utf-8 -*-
"""026. Remove Duplicates from Sorted Array.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10W8nHeoqCf3FpA8aQxYbo1e7ZicDxAvN
"""

class Solution(object):
    def removeDuplicates(self, nums):
        """
        :type nums: List[int]
        :rtype: int
        """
        
            
        length = len(nums)
        if length == 1:
            return 1
        # more than 1 element
        else:
            j = 0
            i = 1
            count = 1
            
            for i in range(length):
                if nums[i] != nums[j]:
                    j += 1
                    nums[j] = nums[i]
                    count += 1
            
            return count