# -*- coding: utf-8 -*-
"""33. Search in Rotated Sorted Array.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17T2MI2Ll4reFgxKVSLtdQ925kqf1jsM9
"""

class Solution:
    def search(self, nums: List[int], target: int) -> int:
        if not nums:
            return -1
        
        l=0
        r=len(nums)-1
        while(l<=r):
            mid=(l+r)//2
            if target==nums[mid]:
                return mid
            
            if nums[l]<=nums[mid]:
                if nums[l]<=target<=nums[mid]:
                    r=mid-1
                else:
                    l=mid+1
            else:
                if nums[mid]<=target<=nums[r]:
                    l=mid+1
                else:
                    r=mid-1         
        return -1