# -*- coding: utf-8 -*-
"""39. Combination Sum.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L8jeLukbQ-L-WakJORVWwlk8_c5SswiU
"""

class Solution(object):
    def combinationSum(self, candidates, target):
        """
        :type candidates: List[int]
        :type target: int
        :rtype: List[List[int]]
        """
        res = []
        combination = []
        def helper(val, i):
          if val > target or i == len(candidates):
            return
          if val == target:
            res.append(combination[:])
            return
        
          combination.append(candidates[i])
			    helper(val + candidates[i], i)
			    combination.pop()
			    helper(val, i + 1)
            
        helper(0, 0)
        return res