# -*- coding: utf-8 -*-
"""48. Rotate Image.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18unoW2Wl6ahvL-faPtep4idNvlcEnqLw
"""

class Solution:
    def rotate(self, a: List[List[int]]) -> None:
        """
        Do not return anything, modify matrix in-place instead.
        """
        a.reverse()
        for i in range(len(a)):
            for j in range(i):
                a[i][j], a[j][i] = a[j][i], a[i][j]