# -*- coding: utf-8 -*-
"""53. Maximum Subarray.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WzkZZumLrD2CAPSZFUgUbQGMNzkBd5Tu
"""

class Solution:
    def maxSubArray(self, nums: List[int]) -> int:
        maxsub = nums[0]
        
        cumsum = 0
        
        for num in nums:
            if cumsum<0:
                cumsum =0
            cumsum +=num
            maxsub = max(cumsum, maxsub)
        
        return maxsub