# -*- coding: utf-8 -*-
"""55. Jump Game.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jefrR4AloYQM4d0UjnnH7yInFTFLx1SV
"""

class Solution:
    def canJump(self, nums: List[int]) -> bool:
        capacity = nums[0]
        
        for x in nums[1:]:
            if capacity <= 0:
                return False
            capacity = max(capacity - 1, x)
            
        return True