# -*- coding: utf-8 -*-
"""58. Length of Last Word.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BSRndFG9E2EgmZXrF22dbQdV67AU1UQ1
"""

def lengthOfLastWord(s):
  s = s.split(' ')
  for i in range(len(s)-1, -1,-1):
    if s[i] != '':
      return len(s[i])