# -*- coding: utf-8 -*-
"""66. Plus One.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15mrBHqOvSFspdYiJ2TCqIWW_0mlue1hr
"""

class Solution:
    def plusOne(self, digits: List[int]) -> List[int]:
        digits = int("".join([str(x) for x in digits]))
        digits += 1
        return list(str(digits))