# -*- coding: utf-8 -*-
"""70. Climbing Stairs.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F9ZJxO1f0qt7cds8FnD50to32ptwJk2Y
"""

class Solution:

  '''
  Core Idea: the number of ways to get to n-th stair is the sum of the ways to
  get to n-1 and n-2
  '''
  def climbStairs(self, n: int) -> int:
    dp = [1,1]
        
    for i in range(2,n+1):
      dp.append(dp[i-1]+dp[i-2])
        
    return dp[n]