# -*- coding: utf-8 -*-
"""91. Decode Ways.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nwY9Wvewh4bYuaKC-n6A4Hi4yU0IHX40
"""

class Solution:
    def numDecodings(self, s: str) -> int:
        def loop(s, memo={}):
            if s in memo:
                return memo[s]
            if s == "":
                return True
            possible_strings = list(map(str, list(range(1, 27))))
            total_ways = 0
            for string in possible_strings:
                if string == s[:len(string)]:
                    total_ways += loop(s[len(string):], memo)

            memo[s] = total_ways
            return total_ways

        return loop(s)