# -*- coding: utf-8 -*-
"""100. Same Tree.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eLwrv35g_EZfgCtfKROzUC0CbvaXv9_0
"""

# Definition for a binary tree node.
# class TreeNode:
#     def __init__(self, val=0, left=None, right=None):
#         self.val = val
#         self.left = left
#         self.right = right
class Solution:
    def isSameTree(self, p: Optional[TreeNode], q: Optional[TreeNode]) -> bool:
        
        if p and q:
            if p.val != q.val:
                return False
            else:
                left_ans = self.isSameTree(p.left, q.left)
                right_ans = self.isSameTree(p.right, q.right)
                return left_ans and right_ans
        else:
            if p is None and q is None:
                return True
            else:
                return False