# -*- coding: utf-8 -*-
"""101. Symmetric Tree.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19FLPWPQsiT3faATZTYtsaK0XXXqyTjdy
"""

# Definition for a binary tree node.
# class TreeNode:
#     def __init__(self, val=0, left=None, right=None):
#         self.val = val
#         self.left = left
#         self.right = right
class Solution:
    def isSymmetric(self, root: Optional[TreeNode]) -> bool:
        def isSym(n1 = root, n2 = root):
            if not (n1 or n2):
                return True
            elif not (n1 and n2):
                return False
            elif n1.val != n2.val:
                return False
            return isSym(n1.left, n2.right) and isSym(n1.right, n2.left)
        return isSym()