# -*- coding: utf-8 -*-
"""125. Valid Palindrome.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Cyl5p9X0PiSre-dJBZYh6R71ElsJ1j1I
"""

class Solution:
    def isPalindrome(self, s: str) -> bool:
        alnum = ""
        for letter in s:
            if letter.isalnum(): # checking for alphanumeric
                alnum += letter.lower()
        return alnum == alnum[::-1]