# -*- coding: utf-8 -*-
"""128. Longest Consecutive Sequence.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BQFSIOp38eqbK31Y1TpoCVbeCO26x5mu
"""

class Solution:
    def longestConsecutive(self, nums: List[int]) -> int:
        ls = set(nums)
        longest = 0
        
        for n in nums:
            if (n-1) not in ls:
                length = 0
                while (n+length) in ls:
                    length +=1
                longest = max(length, longest)
        return longest