# -*- coding: utf-8 -*-
"""144. Binary Tree Preorder Traversal.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NEyQMkk0s0S_FlMRp1oxcjYp55urg0X4
"""

# Definition for a binary tree node.
# class TreeNode:
#     def __init__(self, val=0, left=None, right=None):
#         self.val = val
#         self.left = left
#         self.right = right
class Solution:
    def preorderTraversal(self, root: Optional[TreeNode]) -> List[int]:
        output = []
        if root:
            
            output.append(root.val)
            
            output += self.preorderTraversal(root.left)
            
            output += self.preorderTraversal(root.right)
        return output