# -*- coding: utf-8 -*-
"""169. Majority Element.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cRDURNYg-JwJ0VS71uOpylq7xDS6U0yK
"""

class Solution(object):
    def majorityElement(self, nums):
        """
        :type nums: List[int]
        :rtype: int
        """
        
        if len(nums)==1:
            return nums[0]
        count = {}
        for i in range(len(nums)):
            if nums[i] not in count.keys():
                count.update({nums[i]: 1})
            else:
                count[nums[i]] += 1
                if count[nums[i]] > len(nums)/2:
                    return nums[i]