# -*- coding: utf-8 -*-
"""170. Two Sum III - Data structure design.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YkqJFhtSExYObDwtsDXDHftDpY2bpvEp
"""

class TwoSum:

    def __init__(self):
        self.ctr = collections.defaultdict(int)

    def add(self, number):
        self.ctr[number] += 1

    def find(self, value):
        ctr = self.ctr
        return any(value - num in ctr and (value - num != num or ctr[num] > 1)
                   for num in ctr)

# Your TwoSum object will be instantiated and called as such:
# obj = TwoSum()
# obj.add(number)
# param_2 = obj.find(value)