# -*- coding: utf-8 -*-
"""186. Reverse Words in a String II.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VgTbQr57jfl3NbRsKrTZLTiaE608pYnY
"""

class Solution:
    def reverseWords(self, s: List[str]) -> None:
        """
        Do not return anything, modify s in-place instead.
        """
        s[:] = list((' ').join(('').join(s).split(' ')[::-1]))[:]