# -*- coding: utf-8 -*-
"""198. House Robber.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dt779nHRpzD5pdmspbrU6BSFK_t7NE3J
"""

class Solution:
    def rob(self, nums: List[int]) -> int:
        rob1,rob2=0,0
        for n in nums:
            tmp=max(n+rob1,rob2)
            rob1=rob2
            rob2=tmp
        return rob2