# -*- coding: utf-8 -*-
"""200. Number of Islands.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l6t6FbU4cGvRe3dc3BMJmooyOwQpxs18
"""

class Solution:
    
    def dfs(self, grid, r, c):
        grid[r][c] = '0'
        coor = [(r, c+1),(r,c-1),(r+1,c),(r-1,c)]
        for row, col in coor:
            if row>=0 and col >=0 and row<len(grid) and col<len(grid[r]) and grid[row][col]=="1":
                self.dfs(grid, row, col)
    
    def numIslands(self, grid: List[List[str]]) -> int:
        
        num = 0
        
            
        for r in range(len(grid)):
            for c in range(len(grid[r])):
                if grid[r][c] == '1':
                    self.dfs(grid, r, c)
                    num = num +1
        
        return num

