# -*- coding: utf-8 -*-
"""221. Maximal Square.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EnNVnKYhA0WPZDRSquDNxSqZS8IVy42Y
"""

class Solution:
    def maximalSquare(self, matrix):
        r = len(matrix)
        c = len(matrix[0])
        
        dp = [[0]*(c+1) for _ in range(r+1)]
        mx = 0
        
        for i in range(r):
            for j in range(c):
                if matrix[i][j]!='0':    
                    dp[i+1][j+1] = min(dp[i][j], dp[i][j+1], dp[i+1][j]) + 1
                    mx = max(mx, int(dp[i+1][j+1]))
            
        print(dp)
        return int(mx)**2

