# -*- coding: utf-8 -*-
"""238. Product of Array Except Self.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c6GVXxg1hyBQa0-tqWCneJyrvnKUNDVT
"""

class Solution:
    def productExceptSelf(self, nums: List[int]) -> List[int]:
        temp=1
        prod=[1]*len(nums)
        
        for i in range(len(nums)):
            prod[i] = temp
            temp = temp*nums[i]
            
        temp=1
        for i in range(len(nums)-1,-1,-1):
            prod[i] = prod[i]* temp
            temp = temp*nums[i]
            
        return prod

