# -*- coding: utf-8 -*-
"""261. Graph Valid Tree.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mUaW-XwTEgKhnxXNtTcVmvFCAhP21UEw
"""

class Solution:
    def validTree(self, n: int, edges: List[List[int]]) -> bool:
        if len(edges) < n - 1:
            return False
        adj = [set() for _ in range(n)]
        for i, j in edges:
            adj[i].add(j)
            adj[j].add(i)
        queue = collections.deque([i for i in range(n) if len(adj[i]) == 1])
        while queue:
            i = queue.popleft()
            if not adj[i]:
                continue
            nb = adj[i].pop()
            adj[nb].discard(i)
            if len(adj[nb]) == 1:
                queue.append(nb)
            
        return all([len(x) == 0 for x in adj])