# -*- coding: utf-8 -*-
"""266. Palindrome Permutation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V0DuWqF5991IBEFoEpmgix74gte-8alC
"""

class Solution:
    def canPermutePalindrome(self, s: str) -> bool:
        d = {}
        
        for i in s:
            if i in d:
                d[i] +=1
            else:
                d[i] = 1
        
        ls = list(d.values())

        res = 0
        for i in ls:
            if i %2 ==1:
                res +=1

        if res >1:
            return False
        else:
            return True