# -*- coding: utf-8 -*-
"""305. Number of Islands II.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RZ0kOCgmj_nQv6JvQaZx21ZKkMC3g-gk
"""

class Solution:
    def numIslands2(self, m: int, n: int, positions: List[List[int]]) -> List[int]:
        disJointSet = DisJointSet()
        disJointSet.forest = [1] * (m*n)
        res = []
        directions = [(1, 0), (-1, 0), (0, 1), (0, -1)]
        for x, y in positions:
            index = x * n + y
            disJointSet.setParent(index)
            for i, j in directions:
                a, b = x + i, y + j
                if 0 <= a < m and 0 <= b < n and a * n + b in disJointSet.parents:
                    disJointSet.Union(index, a * n + b)
            res.append(disJointSet.count)
        return res
                    
class DisJointSet(object):
    
    def __init__(self):
        self.parents = {}
        self.count = 0
        self.forest = []
        
    def Union(self, x, y):
        set1 = self.find(x)
        set2 = self.find(y)
        if set1 != set2:                
            if self.forest[set1] < self.forest[set2]:
                    self.parents[set1] = set2
                    self.forest[set2] += self.forest[set1]
            else:
                self.parents[set2] = set1
                self.forest[set1] += self.forest[set2]
            self.count -= 1
    
    def find(self, i):
        while self.parents[i] != i:
            i = self.parents[i]
        return i
    
    def setParent(self, x):
        if self.parents.get(x): 
            return
        self.parents[x] = x
        self.count += 1