# -*- coding: utf-8 -*-
"""334. Increasing Triplet Subsequence.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IorX78rG3fyL-i_EDin3oXMJO35Gm9ko
"""

class Solution:
    def increasingTriplet(self, nums: List[int]) -> bool:
        first, second = inf, inf
        
        for third in nums:
            if third <= first:
                first = third
            elif third <= second:
                second = third
            else:
                return True
        return False