# -*- coding: utf-8 -*-
"""374. Guess Number Higher or Lower.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xLo3ppY7ce1AulHjMmSyONaPppSARJZq
"""

# The guess API is already defined for you.
# @param num, your guess
# @return -1 if num is higher than the picked number
#          1 if num is lower than the picked number
#          otherwise return 0
# def guess(num: int) -> int:

class Solution:
    def guessNumber(self, n: int) -> int:
        low, high = 1, n
        while True:   
            m = (low+high) // 2
            if guess(m) == 0: return m
            elif guess(m) == 1: low = m+1
            else: high = m-1