# -*- coding: utf-8 -*-
"""377. Combination Sum IV.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QUdf3NawdS2wGC5nw1GZAE9t6UQbxRlt
"""

class Solution:
    def combinationSum4(self, nums: List[int], target: int) -> int:
        d = {i:0 for i in range(target+1)}
        d[0] = 1

        for i in range(1,target+1):
            for j in nums:
                if i-j in d:
                    d[i] += d[i-j]
        
        return d[target]