# -*- coding: utf-8 -*-
"""383. Ransom Note.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MCsIi0G7f8XdRebE57L4KO8dShYVRi3_
"""

class Solution:
    def canConstruct(self, ransomNote: str, magazine: str) -> bool:
        # Since each letter in magazine could only be used once
        # It is impossible to make a ransom with shorter magazine
        magazine = [i for i in magazine]
        ransom = [i for i in ransomNote]
        if len(magazine) < len(ransom):
            return False
        else:
            dict = {i:0 for i in magazine}
            
            
            for word in magazine:
                dict[word] = dict[word]+1
            for word in ransom:
                if dict.get(word,0) == 0:
                    
                    return False
                else:
                    dict[word] -= 1
                
            return True