# -*- coding: utf-8 -*-
"""398. Random Pick Index.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GZPS7iYXcTAwEGpxMVcK5vP_A4ZuMsDB
"""

import random
class Solution:

    def __init__(self, nums: List[int]):
        self.s = nums
        self.poss_mem = dict()
    
    def pick(self, target: int) -> int:
        if target in self.poss_mem:
            poss = self.poss_mem[target]
        else:
            poss = [i for i, n in enumerate(self.s) if n == target]
            self.poss_mem[target] = poss
        return random.choice(poss)