# -*- coding: utf-8 -*-
"""404. Sum of Left Leaves.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AJRSl2PqtHVZYzhAlyA8sa-oissFGhB-
"""

# Definition for a binary tree node.
# class TreeNode:
#     def __init__(self, val=0, left=None, right=None):
#         self.val = val
#         self.left = left
#         self.right = right
class Solution:
    def sumOfLeftLeaves(self, root: Optional[TreeNode]) -> int:
        
        if not root: return 0
        
        summ=0
        
        q = [(root, False)]
        
        while q:
            
            node, is_left = q.pop()
            
            if is_left and not node.left and not node.right:
                summ = summ + node.val
            
            q.append((node.left, True)) if node.left else None
            q.append((node.right,False)) if node.right else None
            
        return summ