# -*- coding: utf-8 -*-
"""463. Island Perimeter.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-DeHBs8QwhsWeOdm6je2XEG5_DaAzKGD
"""

class Solution:
    def islandPerimeter(self, grid: List[List[int]]) -> int:
        per = 0
        
        ROWS, COLS = len(grid), len(grid[0])
        
        def func(r,c):
            
            res = 0
            
            coor = [(r, c+1),(r,c-1),(r+1,c),(r-1,c)]
            
            for row, col in coor:
            
                if row<0 or row>=ROWS or col<0 or col>=COLS:
                    res = res+1
                else:
                    if grid[row][col] == 0:
                        res = res+1
            return res
        
        per = 0
        for i in range(ROWS):
            for j in range(COLS):
                if grid[i][j] == 1:
                    per = per + func(i,j)
                    
        return per