# -*- coding: utf-8 -*-
"""463. Island Perimeter.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QEjn8kgb7eOr0lN6SO35DWjDAGI5vUfo
"""

class Solution:
    def islandPerimeter(self, grid: List[List[int]]) -> int:
        n,m,ans = len(grid),len(grid[0]),0
        for i in range(n):
            for j in range(m):
                if grid[i][j]==1:
                    ans+=(i==0 or grid[i-1][j]==0)+(i==n-1 or grid[i+1][j]==0)+(j==0 or grid[i][j-1]==0)+(j==m-1 or grid[i][j+1]==0)
        return ans