# -*- coding: utf-8 -*-
"""495. Teemo Attacking.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r6BtaoOveag4od8GFfPfclEisiHtpJdW
"""

class Solution:
    def findPoisonedDuration(self, timeSeries: List[int], duration: int) -> int:
        result = 0
        for i in range(len(timeSeries)-1):
            if timeSeries[i+1] - timeSeries[i] >= duration:
                result = result+duration
            else:
                result = result+(timeSeries[i+1] - timeSeries[i])
        result = result+duration
        return result