# -*- coding: utf-8 -*-
"""496. Next Greater Element I.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13iqgjiiR_s1lEduwrxitEdcPHqlOL3df
"""

class Solution:
    def nextGreaterElement(self, nums1: List[int], nums2: List[int]) -> List[int]:
        length = len(nums2)
        lst = []
        for x in nums1:
            ind = nums2.index(x)
            if ind ==  length -1:
                lst.append(-1)
            else:
                for i in range(ind,length):
                    if nums2[i] > x:
                        lst.append(nums2[i])
                        break
                else:
                    lst.append(-1)

        return lst