# -*- coding: utf-8 -*-
"""506. Relative Ranks.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ewt1G-vCAlkIK18H0bnzV5MSqVtILN5k
"""

class Solution:
    def findRelativeRanks(self, score: List[int]) -> List[str]:
        dic = {0:"Gold Medal" , 1:"Silver Medal" , 2:"Bronze Medal"}
        
        post = {}
        
        for i,j in enumerate(sorted(score , reverse = True)):
            
            if i in dic:
                post[j] = dic[i]
            else:
                post[j] = str(i+1)
            
        
        lst = []
        for i in score:
            lst.append(post[i])
                
        return lst

