# -*- coding: utf-8 -*-
"""561. Array Partition I.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Fh7dSarieuXuJQxKRb6CKyseEbBQU4h2
"""

class Solution:
    def arrayPairSum(self, nums: List[int]) -> int:
        nums.sort()
        return sum(nums[0::2])