# -*- coding: utf-8 -*-
"""575. Distribute Candies.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1okUa8-SNmwo2dwHcuj7GqeHXqt-II8NH
"""

class Solution:
    def distributeCandies(self, candyType: List[int]) -> int:
        return min(len(set(candyType)), int(len(candyType)/2))