# -*- coding: utf-8 -*-
"""589. N-ary Tree Preorder Traversal.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qHYNMRCXgMzu1k6jq-yEIcv4hj1RaPUi
"""

"""
# Definition for a Node.
class Node:
    def __init__(self, val=None, children=None):
        self.val = val
        self.children = children
"""

class Solution:
    def preorder(self, root: 'Node') -> List[int]:
        elements=[]
        def order(root):
            if root is None:
                return 
            elements.append(root.val)
            for items in root.children:
                order(items)
        order(root)
        return elements