# -*- coding: utf-8 -*-
"""590. N-ary Tree Postorder Traversal.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SLIqbd7L-Ish4gyL1_wfDTaEC6whEXuC
"""

"""
# Definition for a Node.
class Node:
    def __init__(self, val=None, children=None):
        self.val = val
        self.children = children
"""

class Solution:
    def postorder(self, root: 'Node') -> List[int]:
        elements=[]
        def order(root):
            if root is None:
                return 
            
            for items in root.children:
                order(items)
            elements.append(root.val)
        order(root)
        return elements