# -*- coding: utf-8 -*-
"""595. Big Countries.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17WqwACiK_xwNaWHhyZij9tDPnmoWwKuU
"""

# Write your MySQL query statement below
SELECT name,population,area FROM World WHERE (area>=3000000 OR population>=25000000)