# -*- coding: utf-8 -*-
"""696. Count Binary Substrings.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12AHa51SZEYcdLDYTyj5wjrRl2QXreKpg
"""

class Solution:
    def countBinarySubstrings(self, s: str) -> int:
        prev, cur, res = 0, 1, 0
        for i in range(1, len(s)):
            if s[i] == s[i - 1]:
                cur += 1
            else:
                res += min(prev, cur)
                prev, cur = cur, 1
        return res + min(prev, cur)