# -*- coding: utf-8 -*-
"""705. Design HashSet.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18mh60NAlsAe3pBHnwb8dr7qCarzZDb6t
"""

class MyHashSet:

    def __init__(self):
        self.size = 100
        self.hashset = [[] for _ in range(self.size)]

    def add(self, key: int) -> None:
        hashed_key = hash(key)%self.size
        bucket = self.hashset[hashed_key]
        found_key = False
        for index, record in enumerate(bucket):
            record_key = record
            if record_key == key:
                found_key = True
                break
        if found_key:
            bucket[index] = key
        else:
            bucket.append(key)

    def remove(self, key: int) -> None:
        hashed_key = hash(key)%self.size
        bucket = self.hashset[hashed_key]
        found_key = False
        for index, record in enumerate(bucket):
            record_key = record
            if record_key == key:
                found_key = True
                break
        if found_key:
            del bucket[index]
        
    def contains(self, key: int) -> bool:
        hashed_key = hash(key)%self.size
        bucket = self.hashset[hashed_key]
        found_key = False
        for index, record in enumerate(bucket):
            record_key = record
            if record_key == key:
                found_key = True
                break
        if found_key:
            return True
        else:
            return False
        


# Your MyHashSet object will be instantiated and called as such:
# obj = MyHashSet()
# obj.add(key)
# obj.remove(key)
# param_3 = obj.contains(key)