# -*- coding: utf-8 -*-
"""717. 1-bit and 2-bit Characters.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10aMpVxFZqtfVUxHyOcxXjcZ6U1YRRv_E
"""

class Solution:
    def isOneBitCharacter(self, bits: List[int]) -> bool:
        if bits == [0, 0]  or bits == [0] :
            return True
        elif bits == [1, 0]  or bits == [1, 1] :
            return False
        else:
            if bits[0] == 1:
                return self.isOneBitCharacter(bits[2:])
            else:
                return self.isOneBitCharacter(bits[1:])