# -*- coding: utf-8 -*-
"""724. Find Pivot Index.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b3zghUn2cCj6VhdCWRklppcZ2X1rdsl5
"""

class Solution:
    def pivotIndex(self, nums: List[int]) -> int:
        leftSum=0
        rightSum=0

        rightSum = sum(nums) - nums[0]
        if rightSum==0:
            return 0 # Pivot index is 0

        for j in range(1,len(nums)):
            leftSum+=nums[j-1]
            rightSum-=nums[j]
            if leftSum==rightSum:
                return j # Pivot index is j
        return -1 # No pivot