# -*- coding: utf-8 -*-
"""733. Flood Fill.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hGCVBoM1G4Kab5SDRg-Ab49vozyCq_zT
"""

class Solution:
    def floodFill(self, image: List[List[int]], sr: int, sc: int, color: int) -> List[List[int]]:
        n, m, starting_pixel = len(image), len(image[0]), image[sr][sc]
        queue = set()
        queue.add((sr, sc))
        deltas = [(-1, 0), (0, -1), (1, 0), (0, 1)]
        while queue:
            i, j = queue.pop()
            if image[i][j] == color:
                continue
            image[i][j] = color
            for di, dj in deltas:
                x, y = i + di, j + dj
                if 0 <= x < n and 0 <= y < m and image[x][y] == starting_pixel:
                    queue.add((x, y))
        return image