# -*- coding: utf-8 -*-
"""739. Daily Temperatures.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1udPwLin8Yo9Hgo9lzA7v68sPE7g9HUoc
"""

class Solution:
    def dailyTemperatures(self, temperatures: List[int]) -> List[int]:
        mono_stack = []
        if len(temperatures) == 1:
            return [0]
        
        res = [0]*len(temperatures)
        for i,t in enumerate(temperatures):
            while len(mono_stack)>0 and t>temperatures[mono_stack[-1]]:
                popped_ind = mono_stack.pop()
                res[popped_ind] = i-popped_ind
            mono_stack.append(i)
        return res