# -*- coding: utf-8 -*-
"""796. Rotate String.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ngDoSFfGmIaB9N4t_9HsMkt9P4mw4lcN
"""

class Solution:
    def rotateString(self, s: str, goal: str) -> bool:
        if(len(s)!=len(goal)):
            return False
        if(goal in s+s):
            return True
        else:
            return False

