# -*- coding: utf-8 -*-
"""806. Number of Lines To Write String.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c1YhkNeyBJoFrH7fIIGk7b06c2MG5hxW
"""

class Solution:
    def numberOfLines(self, widths: List[int], s: str) -> List[int]:
        dict1 = {}
        for i in range(97,123):
            dict1[chr(i)] = widths[i-97]
            
        sum1 = 0
        line = 1
        
        for i in range(len(s)):
            if sum1 + dict1[s[i]] <= 100:
                sum1+=dict1[s[i]]        
                
            else:
                sum1 = 0
                sum1+=dict1[s[i]]
                line+=1
                
        return [line,sum1]