# -*- coding: utf-8 -*-
"""829. Consecutive Numbers Sum.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19ZNYOQffQEgyjsGbleR85veekHC6ujEa
"""

class Solution:
    '''
    For a consecutive series with length n starting at a
    Its sum will be target = (a + a+n - 1)*n/2
    Hence, a will be a = (2*target + n - n**2)/(2*n)
    Since for each length, the series combination forming the target is unqiue
    n could be used as the identifying factor
    '''
    def consecutiveNumbersSum(self, target: int) -> int:
        
        count = 0
        
        n=2
        
        while 2*target + n - n**2>0:
            a = (2*target + n - n**2)/(2*n)
            # Make sure that a is an integer number
            if a - int(a) ==0:
                count +=1
            
            n +=1
        return count+1