# -*- coding: utf-8 -*-
"""876. Middle of the Linked List.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Xv1NmQ52zVcswS0-ArBKmxSfwIMV0iEH
"""

# Definition for singly-linked list.
# class ListNode:
#     def __init__(self, val=0, next=None):
#         self.val = val
#         self.next = next
class Solution:
    def middleNode(self, head: Optional[ListNode]) -> Optional[ListNode]:
        if not head.next: return head 

        ptr1, ptr2 = head.next, head                                       

        while ptr1.next and ptr1.next.next:
            ptr1 = ptr1.next.next
            ptr2 = ptr2.next 
            
        return ptr2.next