# -*- coding: utf-8 -*-
"""898. Bitwise ORs of Subarrays.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f8oVFl7xBh5D_15dLz5jqf-e8m2T3uOi
"""

class Solution:
    def subarrayBitwiseORs(self, A: List[int]) -> int:
        ans, vals = set(), set()
        for x in A: 
            vals = {x | xx for xx in vals} | {x}
            ans |= vals
        return len(ans)