# -*- coding: utf-8 -*-
"""905. Sort Array By Parity.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PlFrNQzOyCawUgk9xbgRgC9DTqC0LoUQ
"""

class Solution:
    def sortArrayByParity(self, array: List[int]) -> List[int]:
        left, right = 0, len(array) - 1

        while left < right:
            if array[left] % 2 == 0:
                left += 1
            else:
                array[left], array[right] = array[right], array[left]
                right -= 1

        return array