# -*- coding: utf-8 -*-
"""908. Smallest Range I.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S5-qpMtSJzNMFaDzJr56Saznc4nsG1Kk
"""

class Solution:
    def smallestRangeI(self, nums: List[int], k: int) -> int:
        k_range = 2 * k
        max_value = max(nums)
        min_value = min(nums)
        return max(0, max_value - min_value - k_range)