# -*- coding: utf-8 -*-
"""973. K Closest Points to Origin.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11sGsSPz2qjBY8tXSu97AXDZKjp9X_srk
"""

import heapq

class Solution:
    def kClosest(self, points: List[List[int]], k: int) -> List[List[int]]:
        
        minheap = []

        for x, y in points:
            dis = x**2 + y**2
            minheap.append([dis, x, y])

        heapq.heapify(minheap)

        res = []
        for i in range(k):
            dis, x, y = heapq.heappop(minheap)
            res.append([x,y])

        return res