# -*- coding: utf-8 -*-
"""976. Largest Perimeter Triangle.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RQx6uFsnbhzGR7zGeIX5BSOcK7VWhWCc
"""

class Solution:
    def largestPerimeter(self, nums: List[int]) -> int:

        nums.sort(reverse = True)
        
        while len(nums) > 2 and nums[0] >= nums[1] + nums[2]:
            nums.pop(0)
            
        return 0 if len(nums) < 3 else sum(nums[:3])