# -*- coding: utf-8 -*-
"""1041. Robot Bounded In Circle.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tsNp9u3rkxY5Mc-OO-lqyDpuac0Q1XUE
"""

class Solution:
    '''
    After one entire process, there could be three cases:
    If the position remain the same -> must be in a cycle
    If both position and directions are different -> must be in a cycle
    If directions are the same yet position changes -> not in a cycle
    '''
    
    def isRobotBounded(self, instructions: str) -> bool:
        
        # At the beginning the robot faces north
        dirX, dirY = 0, 1
        x, y = 0, 0
        
        for d in instructions:
            if d == 'G':
                x += dirX
                y += dirY
            elif d == 'L':
                dirX, dirY = -1*dirY, dirX
                
            else:
                dirX, dirY = dirY, -1*dirX
                
        return (x, y) ==(0,0) or (dirX, dirY) != (0, 1)