# -*- coding: utf-8 -*-
"""1086. High Five.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1byt9-44C6gakX9YltmkjZS0N1X-JZ8h4
"""

class Solution:
    def highFive(self, items: List[List[int]]) -> List[List[int]]:
        hm = defaultdict(list)
        ans = []
        for j,i in enumerate(items):
            hm[i[0]].append(i[1])
            
        for id_,score in hm.items():
            top_5 = sorted(score, reverse=True)[:5]
            average = int(sum(top_5)/5)
            ans.append([id_,average])
        ans.sort()
        return ans