# -*- coding: utf-8 -*-
"""1099. Two Sum Less Than K.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XrcW4J50Xjb3FKBYdzjYAdF-sTYOaX4u
"""

class Solution:
    def twoSumLessThanK(self, nums: List[int], k: int) -> int:
        
        nums.sort()
        if len(nums) <2:
            return -1
        elif nums[0]+nums[1] >= k:
            return -1
        else:
            l = 0
            r = len(nums)-1
            res = 0
            while l < r:
                sum = nums[l] +nums[r] 
                if sum < k:
                    res = max(res, sum)
                    l +=1
                else:
                    r -=1
            return res