# -*- coding: utf-8 -*-
"""1137. N-th Tribonacci Number.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_lHPoI8eKB9rLqbPLrdW_F7peIN8zidS
"""

class Solution:
    def tribonacci(self, n: int) -> int:
        res = [0, 1, 1]
        
        for i in range(3, n+1):
            res.append(res[i-3]+res[i-2]+res[i-1])
        
        return res[n]