# -*- coding: utf-8 -*-
"""1154. Day of the Year.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GtgZlh5EoeAEsaK4g1fM92yOxV1vlGdB
"""

class Solution:
    def dayOfYear(self, date: str) -> int:
        numDaysPassed = [0, 31, 59, 90, 120, 151, 181, 212, 243, 273, 304, 334, 365]
        year, month, day = int(date[0:4]), int(date[5:7]), int(date[8:10])
        if year % 4 == 0 and month > 2:
            if year % 100 != 0 or year % 400 == 0:
                return numDaysPassed[month - 1] + day + 1
        return numDaysPassed[month - 1] + day