# -*- coding: utf-8 -*-
"""1207. Unique Number of Occurrences.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1anUAmzCBhyWAtWLxX9GLSJuLzP0-KOj6
"""

class Solution:
    def uniqueOccurrences(self, arr: List[int]) -> bool:
        from collections import Counter
        counter = Counter(arr)
        freq = list(counter.values())
        return(len(freq) == len(set(freq)))