# -*- coding: utf-8 -*-
"""1230. Toss Strange Coins.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SM6VHzwZbfxEWjuHojVTViPKUlHiFnHz
"""

class Solution:
    def probabilityOfHeads(self, prob: List[float], target: int) -> float:
        dp = [0] * (target+1)
        dp[0] = 1
        for n in range(len(prob)):
            head = prob[n]
            for i in range(target, 0, -1): #inverse order
                dp[i] = dp[i] * (1-head) + dp[i-1] * head
            dp[0] = dp[0] * (1-head)
        return dp[-1]