# -*- coding: utf-8 -*-
"""1268. Search Suggestions System.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HDvXk8lKHLY58C8FZeX05g87src4fPV1
"""

class Solution:
    def suggestedProducts(self, products: List[str], searchWord: str) -> List[List[str]]:
        products.sort()
        n=len(products)
        indices=[i for i in range(n)]
        res=[]
        for idx, c in enumerate(searchWord):
            indices = [i for i in indices if len(products[i])>idx and products[i][idx] == c]                                                                
            res.append(products[i] for i in indices[:3])        
        return res