# -*- coding: utf-8 -*-
"""1275. Find Winner on a Tic Tac Toe Game.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UGdD40CtU5VJvi4yzFGTd-6auQXlVtQA
"""

class Solution:
    def tictactoe(self, moves: List[List[int]]) -> str:
        movesA = moves[::2]
        movesB = moves[1::2]
        
        # for A
        if len(movesA) > 2:
            # check if diagonal
        
            if [0, 0] in movesA and [1, 1] in movesA and [2, 2] in movesA:
                return "A"

            if [0, 2] in movesA and [1, 1] in movesA and [2, 0] in movesA:
                return "A"

            # check horizontal
            for i in range(3):
                if [i, 0] in movesA and [i, 1] in movesA and [i, 2] in movesA:
                    return "A"
            
            # check vertical
            for i in range(3):
                if [0, i] in movesA and [1, i] in movesA and [2, i] in movesA:
                    return "A"
            
        # for B
        if len(movesB) > 2:
            if [0, 0] in movesB and [1, 1] in movesB and [2, 2] in movesB:
                return "B"

            if [0, 2] in movesB and [1, 1] in movesB and [2, 0] in movesB:
                return "B"

            # check horizontal
            for i in range(3):
                if [i, 0] in movesB and [i, 1] in movesB and [i, 2] in movesB:
                    return "B"
            
            # check vertical
            for i in range(3):
                if [0, i] in movesB and [1, i] in movesB and [2, i] in movesB:
                    return "B"
        
        # draw or pending
        if len(moves) == 9:
            return "Draw"
        
        return "Pending"