# -*- coding: utf-8 -*-
"""1328. Break a Palindrome.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qMfwb1LI-lbXxRP8aygdz9j9JNMuuaJB
"""

class Solution:
  '''
  Core idea: Change the very first element that is not "a" to "a"
  If all elements are "a"s, then change the last to "b
  '''
  def breakPalindrome(self,s: str) -> str:
    n = len(s)
    if n == 1:
        return ''
    for i in range(n//2):
        if s[i] != 'a':
            return s[:i] + 'a' + s[i+1:]
    return s[:-1] + 'b'