# -*- coding: utf-8 -*-
"""1366. Rank Teams by Votes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n02phpkQNPOuKu8QXeTBzyZ_O3I_y6O-
"""

class Solution:
    def rankTeams(self, votes: List[str]) -> str:
        voteslen, wordlen = len(votes), len(votes[0])
        votes_by_team = dict()
        for i in range(wordlen):
            votes_by_team[votes[0][i]] = [0] * wordlen
        for pos in range(wordlen):
            for vote in range(voteslen):
                votes_by_team[votes[vote][pos]][pos] -= 1
        list_to_cmp = [ v + [k] for k, v in votes_by_team.items() ]
        list_to_cmp.sort()
        return ''.join([x[-1] for x in list_to_cmp])