# -*- coding: utf-8 -*-
"""1380. Lucky Numbers in a Matrix.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n1MNbmXratOpBNqAhjtnf6cS_o1JG3d9
"""

class Solution:
    def luckyNumbers (self, matrix: List[List[int]]) -> List[int]:
        minRow = []
        maxCol = []
        
        # for minimum in row!         
        for i in matrix:
            minRow.append(min(i))
        
        # for maximum in column!
        for i in range(len(matrix[0])):
            curr = matrix[0][i]
            
            for j in range(len(matrix)):
                if matrix[j][i] >= curr:
                    curr = matrix[j][i]
            
            maxCol.append(curr)
        
        fin = []
        for i in maxCol:
            if i in minRow:
                fin.append(i)
        
        return fin