# -*- coding: utf-8 -*-
"""1395. Count Number of Teams.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UmjNAV1uCT7QG8bM8zDXk7oQDuQBWnFT
"""

class Solution:
    def numTeams(self, rating: List[int]) -> int:
        up=[0 for i in range(len(rating))]
        down=[0 for i in range(len(rating))]
        c=0                   
        for i in range(len(rating)):
            for j in range(i):
                if rating[i]>rating[j]:
                    c+=up[j]
                    up[i]+=1
                else:
                    c+=down[j]
                    down[i]+=1
        return c