# -*- coding: utf-8 -*-
"""1446. Consecutive Characters.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fA9_2NBro1w82R1ZfkJhFemugGE0tWDt
"""

class Solution:
    def maxPower(self, s: str) -> int:
        i, power, maxPower = 1,1,1
        N = len(s)
        
        while(i < N):
            if s[i] == s[i-1]:
                power += 1
                maxPower = max(maxPower, power)
            else:
                power = 1
            i += 1
        
        return maxPower