# -*- coding: utf-8 -*-
"""1476. Subrectangle Queries.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pwez1ZNFymsATUTOzvWN8by--PaiAF5d
"""

class SubrectangleQueries:

    def __init__(self, rectangle: List[List[int]]):
        self.rectangle = rectangle
        

    def updateSubrectangle(self, row1: int, col1: int, row2: int, col2: int, newValue: int) -> None:
        for i in range(row1, row2+1):
            for j in range(col1, col2+1):
                self.rectangle[i][j]=newValue
        

    def getValue(self, row: int, col: int) -> int:
        return self.rectangle[row][col]