# -*- coding: utf-8 -*-
"""1710. Maximum Units on a Truck.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tNAy0YrZN_JyY_gsEFJnvuyDqBgdHgTq
"""

class Solution:
    def maximumUnits(self, boxTypes: List[List[int]], truckSize: int) -> int:
        boxTypes.sort(key=lambda x:x[1],reverse=True)
        max_val =0
        for x,y in boxTypes:
            if x <= truckSize and truckSize > 0:
                max_val += x * y
                truckSize -=x
            else:
                max_val += truckSize * y
                truckSize -= truckSize
        return max_val