# -*- coding: utf-8 -*-
"""1769. Minimum Number of Operations to Move All Balls to Each Box.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mRdm7_4xB00zpXY3Y57aucS0cO7cRCYC
"""

class Solution:
    def minOperations(self, boxes: str) -> List[int]:
        l=[i for i in range(0,len(boxes)) if boxes[i]=="1"]
        m=[]
        s=0
        for i in range(0,len(boxes)):
            for j in l:
                s+=abs(j-i)
            m.append(s)
            s=0
        return m