# -*- coding: utf-8 -*-
"""1779. Find Nearest Point That Has the Same X or Y Coordinate.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/195rB8n5CUmfdpcS_pJv9IvhxnczLjRMY
"""

class Solution:
    def nearestValidPoint(self, x: int, y: int, points: List[List[int]]) -> int:

        dic={}
        iterate=0
        for i in points:
            if(i[0]==x or i[1]==y):
                dic[iterate]=dic.get(iterate,0)+(abs(i[0]-x)+abs(i[1]-y))
            iterate+=1    

        if(len(dic)==0):
            return -1
        for k,v in sorted(dic.items(), key=lambda x:x[1]):
            return k