# -*- coding: utf-8 -*-
"""183. Customers Who Never Order.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sYR4yh72eAdbKFa5YlDWjPgoU5_1oQ5K
"""

# Write your MySQL query statement below
SELECT name AS Customers
FROM Customers
LEFT JOIN Orders
ON Customers.id = Orders.customerId
WHERE Orders.customerId IS null;