# -*- coding: utf-8 -*-
"""2016. Maximum Difference Between Increasing Elements.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hP6aqnP4YnGqBLz6NDw30lwsFkJnB8eT
"""

class Solution:
    def maximumDifference(self, nums: List[int]) -> int:
        ans = 0
        for i in range(len(nums)-1):
            ans = max(ans, max(nums[i+1 :]) - nums[i])
            
        if ans == 0:
            return -1
        return ans