# -*- coding: utf-8 -*-
"""2057. Smallest Index With Equal Value.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uLxDChmPmnYVcAbO19UaapS611mnO9U0
"""

class Solution:
    def smallestEqual(self, nums: List[int]) -> int:
        for i,num in enumerate(nums):
            if i%10==num:
                return i
        
        return -1