# -*- coding: utf-8 -*-
"""2128. Remove All Ones With Row and Column Flips.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16Wls4IIt91fuHdEjzlV0m0i2186mM95q
"""

class Solution:
    def removeOnes(self, grid: List[List[int]]) -> bool:
        for i in range(len(grid)):
            
            # invert the row if the first value is 1 so we can have equivalent comparisons
            if grid[i][0] == 1:
                for j in range(len(grid[i])):
                    if grid[i][j] == 0:
                        grid[i][j] = 1
                    else:
                        grid[i][j] = 0
                        
            # check if current row is equivalent to the first one
            if grid[i] != grid[0]:
                return False
            
        # if we finish the loop then it's a solvable graph
        return True