# -*- coding: utf-8 -*-
"""2149. Rearrange Array Elements by Sign.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y2PXhEyIald1pZ_04imT-uRDucwxbdnH
"""

class Solution:
    def rearrangeArray(self, nums: List[int]) -> List[int]:
        answer = [0] * len(nums)
        
		# positive and negative pointers
        p,n = 0,1
        
		# helper function to determine positive/negative num
        def is_pos(num): return num > 0
        
        for num in nums:
            if is_pos(num):
                answer[p] = num
                p += 2
            else:
                answer[n] = num
                n += 2
                
        return answer