# -*- coding: utf-8 -*-
"""21. Merge Two Sorted Lists.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rQ8XB4Un2Dbi9fziVi26dH0cJWvZde9n
"""

class Solution:

    def mergeTwoLists(self, list1: Optional[ListNode], list2: Optional[ListNode]) -> Optional[ListNode]:
        if not list1:
            return list2
        elif not list2:
            return list1
        else:
            if list1.val <= list2.val:
                merged_list = ListNode(val=list1.val)
                merged_list.next = self.mergeTwoLists(list1.next, list2)
            else:
                merged_list = ListNode(val=list2.val)
                merged_list.next = self.mergeTwoLists(list1, list2.next)
            
        return merged_list