# -*- coding: utf-8 -*-
"""2210. Count Hills and Valleys in an Array.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ia4Pn1q5BkcIo8zNbjqkisMo4D_tvwdB
"""

class Solution:
    def countHillValley(self, nums: List[int]) -> int:
        new_nums = [(nums[0], 0)]
        same = defaultdict(int)
        for i in range(1, len(nums)):
            if nums[i] == nums[i-1]:
                same[i] += 1
            else:
                new_nums.append((nums[i], i))
        
        if len(new_nums) <= 2:
            return 0
        
        total = 0
        for i in range(1, len(new_nums)-1):
            if new_nums[i-1][0] < new_nums[i][0] > new_nums[i+1][0]:
                total += 1 + same[new_nums[i][1]]
            elif new_nums[i-1][0] > new_nums[i][0] < new_nums[i+1][0]:
                total += 1 + same[new_nums[i][1]]

        return total