# -*- coding: utf-8 -*-
"""268. Missing Number.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cqfljn0auDIoGOWuyeuz4j1FGh1ITzYc
"""

class Solution:
    def missingNumber(self, nums: List[int]) -> int:
        correct_sum = sum(range(len(nums)))
        nums_sum = sum(nums)
        if nums_sum == correct_sum:
            return len(nums)
        else:
            diff = nums_sum - correct_sum
            return len(nums)-diff