# -*- coding: utf-8 -*-
"""283. Move Zeroes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wVErrT1dTFJ7prwaQ9q8Cb4gexZpam8a
"""

class Solution:
    def moveZeroes(self, nums: List[int]) -> None:
        """
        Do not return anything, modify nums in-place instead.
        """
        
        try:
            while True:
                nums.remove(0)
                nums.append('a')
        except ValueError:
            pass
        for i in range(len(nums)):
            if nums[i] == 'a':
                nums[i] = 0