# -*- coding: utf-8 -*-
"""35. Search Insert Position.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lIyjJtne8RRETj7dqVdqfbfKIStCCwwR
"""

class Solution:
    def searchInsert(self, nums: List[int], target: int) -> int:
        if nums[0] > target:
            return 0
        first_index = 0
        last_index = len(nums) - 1
        while first_index <= last_index:
            midpoint = (first_index + last_index)//2
            if nums[midpoint] == target: 
                return midpoint
            elif nums[midpoint] > target:
                last_index = midpoint - 1
            else:
                first_index = midpoint + 1
        if nums[midpoint] > target:
            if nums[midpoint - 1] < target:
                return midpoint
            return midpoint -1
        return midpoint + 1