# -*- coding: utf-8 -*-
"""414. Third Maximum Number.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12Cbo5SGw34CnsEU8kU6d-msrcBCP5ymT
"""

class Solution:
    def thirdMax(self, nums: List[int]) -> int:
        if len(set(nums))<3:
            return max(nums)
        else:
            nums=list(set(nums))
            heapq.heapify(nums)
            return heapq.nlargest(3,nums)[-1]