# -*- coding: utf-8 -*-
"""455. Assign Cookies.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ecVmvfgVfs4waNHNEz0pbaYPoE7SUV9E
"""

class Solution:
    def findContentChildren(self, g: List[int], s: List[int]) -> int:
        g.sort()
        s.sort()
        counter: int = 0
        size_g: int = len(g)
        for cookie in s:
            if counter >= size_g:
                break
            if g[counter] <= cookie:
                counter += 1
        
        return counter