# -*- coding: utf-8 -*-
"""485. Max Consecutive Ones.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D2E_vG2HAomQ-9KsTBSeenze8tRlixSJ
"""

class Solution:
    def findMaxConsecutiveOnes(self, nums: List[int]) -> int:
        maxOne = 0
        i,j=0,0
        while j < len(nums):
            if nums[j] == 1:
                maxOne = max(j-i+1,maxOne)
                j+=1
            else:
                j+=1
                i=j
        return maxOne