# -*- coding: utf-8 -*-
"""500. Keyboard Row.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gDdDUucgyDv6rSSTx-shlGOKTrOL8U9S
"""

class Solution:
    def findWords(self, words: List[str]) -> List[str]:
        l1 = set("qwertyuiop")
        l2 = set("asdfghjkl")
        l3 = set("zxcvbnm")
        result = []
        for i in words:
            word = set(i.lower())
            len1 = len(l1.union(word))
            len2 = len(l2.union(word))
            len3 = len(l3.union(word))
            if len1 == len(l1) or len2 == len(l2) or len3 == len(l3):
                result.append(i)
        
        return result