# -*- coding: utf-8 -*-
"""584. Find Customer Referee.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jpYWxSG2H3G3fHAWRLvLgLpVMViXQqzl
"""

SELECT name FROM Customer WHERE referee_id != 2 OR referee_id IS NULL

