# -*- coding: utf-8 -*-
"""746. Min Cost Climbing Stairs.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1567Ps0yde1ekXtrTkpKmHDpWmzczMy6l
"""

class Solution:
    def minCostClimbingStairs(self, cost: List[int]) -> int:
        if(len(cost)==2):
            return min(cost)
        cost.append(0)
        for i in range(len(cost)-3,-1,-1):
            cost[i] = cost[i] + min(cost[i+1],cost[i+2])
        return min(cost[0],cost[1])



