# -*- coding: utf-8 -*-
"""804. Unique Morse Code Words.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10WdMwP52MSo60xaZmoxUljzBqpHsVFC2
"""

class Solution:
    def uniqueMorseRepresentations(self, words: List[str]) -> int:
        l=[".-","-...","-.-.","-..",".","..-.","--.","....","..",
           ".---","-.-",".-..","--","-.","---",".--.","--.-",".-.","...",
           "-","..-","...-",".--","-..-","-.--","--.."]
        s="abcdefghijklmnopqrstuvwxyz"
        d={}
        for i in range(len(l)):
            d[s[i]]=l[i]
        se=set()
        for i in range(len(words)):
            st=""
            for j in words[i]:
                st=st+d[j]
            se.add(st)
        return len(se)