# -*- coding: utf-8 -*-
"""961. N-Repeated Element in Size 2N Array.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U4UTReUWzQ_qZYrtC4HstlhK9k8ruQZz
"""

class Solution:
    def repeatedNTimes(self, nums: List[int]) -> int:
        unique = set(nums)
        diff = sum(nums) - sum(unique)
        return int(diff/(len(unique)-2))